### ISSUE TITLE
如何使用破解出的global-metadata.bat

### ISSUE THREAD

**Issue by wangsy1985** [b1ueb1ues/dlre2#1]
最近在研究用IDA pro破解Unity游戏的源代码，还处在入门阶段。
目前可以用global-metadata.bat来查看游戏的源代码了。

想问问您现在这个项目是用来做什么的？
破解出源代码后还可以做哪些事情呢？
谢谢😄

**Comment by b1ueb1ues** [comment]
hook然后动态查看/修改程序逻辑

**Comment by b1ueb1ues** [comment]
比如制作伤害统计插件
创造木桩房等等
